[tools]
bat = "latest"
btop = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "lts"
rg = "latest"
ruby = "3.4"
usage = "latest"
watchexec = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []

